[project]
name = "embedding-atlas"
version = "0.8.0"
license = "MIT"
description = "A tool for visualizing embeddings"
keywords = ["embedding", "visualization"]
readme = "README.md"
authors = [
  {name = "Donghao Ren", email = "donghao.ren@gmail.com"},
  {name = "Halden Lin", email = "halden.lin@gmail.com"},
  {name = "Fred Hohman", email = "fredhohman@apple.com"},
  {name = "Dominik Moritz", email = "domoritz@gmail.com"},
]
requires-python = ">=3.10"
dependencies = [
  "click >= 8.0.0",
  "pandas >= 2.3.0",
  "fastparquet >= 2024.0.0",
  "platformdirs >= 4.3.0",
  "umap-learn >= 0.5.0",
  "sentence-transformers >= 5.0.0",
  "fastapi >= 0.116.0",
  "uvicorn >= 0.35.0",
  "uvloop >= 0.21.0",
  "pyarrow >= 21.0.0",
  "duckdb >= 1.3.2",
  "inquirer >= 3.0.0",
  "llvmlite >= 0.44.0",
  "accelerate >= 1.9.0",
  "tqdm >= 4.67.0",
]

[project.scripts]
embedding-atlas = "embedding_atlas.cli:main"

[project.urls]
homepage = "https://apple.github.io/embedding-atlas"
source = "https://github.com/apple/embedding-atlas"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
artifacts = [
  "embedding_atlas/static",
  "embedding_atlas/widget_static"
]

[tool.hatch.build.targets.wheel]
packages = ["embedding_atlas"]

[dependency-groups]
dev = [
  "datasets >= 3.1.0",
  "jupyterlab >= 4.3.0",
  "streamlit >= 1.43.0",
  "anywidget >= 0.9.0",
]
